### ISSUE TITLE
Unable to find eligible runners for Flowzone CI

### ISSUE THREAD

**Issue by klutchell** [balena-io-experimental/container-jail#42]
See: https://balena.fibery.io/Inputs/Research/Figure-out-how-to-CI-test-KVM-features-with-GitHub-Actions-446

The official hosted GitHub runners currently do not support KVM, and our fleet of VM self-hosted runners only support nested KVM on x86.

So the only option for now is to allow the use of our containerized self-hosted runners for some public repos, or just make them private.

**Comment by ab77** [comment]
.. set up a small isolated runners group and whitelist the repos that require nested KVM.

**Comment by klutchell** [comment]
The `kvm-testing` runner group was added to the Balena enterprise and shared with this repo. Two containerized runners were then configured to register to the new runner group.
